### PR TITLE
[GLT-3300] Fix typo in Printer layout

### PR DESCRIPTION
**Pull request by avarsava**
2barcode -> 2dbarcode

### CODE REVIEW

**Comment by djcooke** [comment]
Looks like the typo was made in 3 places - twice [here](https://github.com/miso-lims/miso-lims/blob/develop/sqlstore/src/main/resources/db/migration/V1040__auto_main.sql#L95) and once in the line above. You could replace all instances of `"2barcode"` in the column with `"2dbarcode"`? That would cover cases where the layouts have been modified too.

**Comment by avarsava** [comment]
> Looks like the typo was made in 3 places - twice [here](https://github.com/miso-lims/miso-lims/blob/develop/sqlstore/src/main/resources/db/migration/V1040__auto_main.sql#L95) and once in the line above. You could replace all instances of `"2barcode"` in the column with `"2dbarcode"`? That would cover cases where the layouts have been modified too.

Updated the migration to affect the BASE64 layout too. Not sure how we could affect layouts if they've been modified?

**Comment by djcooke** [comment]
```
UPDATE Printer
SET layout = REPLACE(layout, '"2barcode"', '"2dbarcode"');
```

**Comment by avarsava** [comment]
> ```
> UPDATE Printer
> SET layout = REPLACE(layout, '"2barcode"', '"2dbarcode"');
> ```

Updated

**Pull request merged**
